export type VendorTaxonomyCategoryDefinition = {
  code: string;
  name: string;
  subcategories: Array<{
    code: string;
    name: string;
  }>;
};

export type CountryCatalogEntry = {
  code: string;
  name: string;
  regionGroup: string;
  cities: Array<{
    name: string;
    region: string;
  }>;
};

export const VENDOR_TAXONOMY: VendorTaxonomyCategoryDefinition[] = [
  {
    code: "EV-BLD",
    name: "Build & Infrastructure",
    subcategories: [
      { code: "EV-BLD-01", name: "Structures / Gates / Tunnels" },
      { code: "EV-BLD-02", name: "Booths / Kiosks / Pavilions" },
      { code: "EV-BLD-03", name: "Scenic / Decor / Backdrops" },
      { code: "EV-BLD-04", name: "Finishes / Flooring / Painting" },
      { code: "EV-BLD-05", name: "Signage Fabrication & Install" },
      { code: "EV-BLD-06", name: "MEP / Temporary Civil Works" },
    ],
  },
  {
    code: "EV-PRO",
    name: "Production & Show",
    subcategories: [
      { code: "EV-PRO-01", name: "Production Management / PMO" },
      { code: "EV-PRO-02", name: "Stage / Platforms / Backstage" },
      { code: "EV-PRO-03", name: "Rigging / Engineering" },
      { code: "EV-PRO-04", name: "Run of Show / Rehearsals" },
      { code: "EV-PRO-05", name: "Production Office / Comms" },
      { code: "EV-PRO-06", name: "Consultants / Advisory" },
      { code: "EV-PRO-07", name: "Engineering Certification / TUV" },
      { code: "EV-PRO-08", name: "Submittals / Documentation" },
      { code: "EV-PRO-09", name: "Testing / Commissioning" },
    ],
  },
  {
    code: "EV-AVL",
    name: "Audio Video Lighting",
    subcategories: [
      { code: "EV-AVL-01", name: "Audio Systems" },
      { code: "EV-AVL-02", name: "LED / Screens / Projection" },
      { code: "EV-AVL-03", name: "Lighting Systems" },
      { code: "EV-AVL-04", name: "Camera / Broadcast" },
      { code: "EV-AVL-05", name: "Special Effects / Lasers" },
      { code: "EV-AVL-06", name: "AV Control / Cabling" },
    ],
  },
  {
    code: "EV-EXP",
    name: "Experiences & Activations",
    subcategories: [
      { code: "EV-EXP-01", name: "Immersive Experiences" },
      { code: "EV-EXP-02", name: "Interactive Activities" },
      { code: "EV-EXP-03", name: "Gaming / VR" },
      { code: "EV-EXP-04", name: "Workshops / Education" },
      { code: "EV-EXP-05", name: "Brand Activations" },
      { code: "EV-EXP-06", name: "Talent / Performers" },
    ],
  },
  {
    code: "EV-FNB",
    name: "Food & Beverage",
    subcategories: [
      { code: "EV-FNB-01", name: "Catering" },
      { code: "EV-FNB-02", name: "Food Booths" },
      { code: "EV-FNB-03", name: "Beverage / Bars" },
      { code: "EV-FNB-04", name: "Kitchen / Hygiene" },
      { code: "EV-FNB-05", name: "F&B Payments" },
      { code: "EV-FNB-06", name: "F&B Consumables" },
    ],
  },
  {
    code: "EV-OPS",
    name: "Operations & Logistics",
    subcategories: [
      { code: "EV-OPS-01", name: "Site Operations" },
      { code: "EV-OPS-02", name: "Logistics / Freight" },
      { code: "EV-OPS-03", name: "Transportation / Fleet" },
      { code: "EV-OPS-04", name: "Electrical Works & Power" },
      { code: "EV-OPS-05", name: "Utilities (Water/HVAC)" },
      { code: "EV-OPS-06", name: "Cleaning / Waste / Toilets" },
      { code: "EV-OPS-07", name: "IT Connectivity" },
      { code: "EV-OPS-08", name: "Venue Rental / Site Lease" },
      { code: "EV-OPS-09", name: "Equipment / Furniture Rental" },
      { code: "EV-OPS-10", name: "Standby / Emergency Services" },
    ],
  },
  {
    code: "EV-STA",
    name: "Staffing & Workforce",
    subcategories: [
      { code: "EV-STA-01", name: "Crew / Technicians" },
      { code: "EV-STA-02", name: "FOH Staff" },
      { code: "EV-STA-03", name: "Security Manpower" },
      { code: "EV-STA-04", name: "HR / Scheduling" },
      { code: "EV-STA-05", name: "Uniforms / IDs" },
      { code: "EV-STA-06", name: "Freelancers / Specialists" },
    ],
  },
  {
    code: "EV-SEC",
    name: "Security, Safety & Compliance",
    subcategories: [
      { code: "EV-SEC-01", name: "Security Systems" },
      { code: "EV-SEC-02", name: "Safety Compliance" },
      { code: "EV-SEC-03", name: "Medical Services" },
      { code: "EV-SEC-04", name: "Permits / Civil Defense" },
      { code: "EV-SEC-05", name: "Risk / Insurance" },
      { code: "EV-SEC-06", name: "Government Fees" },
      { code: "EV-SEC-07", name: "Event Insurance" },
      { code: "EV-SEC-08", name: "Equipment Insurance" },
      { code: "EV-SEC-09", name: "Sustainability / ESG" },
    ],
  },
  {
    code: "EV-GST",
    name: "Guest & Hospitality",
    subcategories: [
      { code: "EV-GST-01", name: "VIP Services" },
      { code: "EV-GST-02", name: "Access / Ticketing" },
      { code: "EV-GST-03", name: "Travel / Accommodation" },
      { code: "EV-GST-04", name: "Backstage Hospitality" },
      { code: "EV-GST-05", name: "Guest Services" },
      { code: "EV-GST-06", name: "Staff Accreditation" },
    ],
  },
  {
    code: "EV-COM",
    name: "Commercial & Business",
    subcategories: [
      { code: "EV-COM-01", name: "Marketing / PR" },
      { code: "EV-COM-02", name: "Sponsorship" },
      { code: "EV-COM-03", name: "Merchandise" },
      { code: "EV-COM-04", name: "Procurement / Contracts" },
      { code: "EV-COM-05", name: "Finance / Cost Control" },
      { code: "EV-COM-06", name: "Talent Contracts" },
    ],
  },
];

export const COUNTRY_CATALOG: CountryCatalogEntry[] = [
  {
    code: "SA",
    name: "Saudi Arabia",
    regionGroup: "GCC",
    cities: [
      { name: "Riyadh", region: "Riyadh Region" },
      { name: "Diriyah", region: "Riyadh Region" },
      { name: "Al Kharj", region: "Riyadh Region" },
      { name: "Al Majmaah", region: "Riyadh Region" },
      { name: "Al Zulfi", region: "Riyadh Region" },
      { name: "Shaqra", region: "Riyadh Region" },
      { name: "Al Dawadmi", region: "Riyadh Region" },
      { name: "Afif", region: "Riyadh Region" },
      { name: "Wadi Al Dawasir", region: "Riyadh Region" },
      { name: "Al Quwayiyah", region: "Riyadh Region" },
      { name: "Hotat Bani Tamim", region: "Riyadh Region" },
      { name: "Al Aflaj", region: "Riyadh Region" },
      { name: "Rumah", region: "Riyadh Region" },
      { name: "Thadiq", region: "Riyadh Region" },
      { name: "Huraymila", region: "Riyadh Region" },
      { name: "Durma", region: "Riyadh Region" },
      { name: "Al Hariq", region: "Riyadh Region" },
      { name: "Layla", region: "Riyadh Region" },
      { name: "Jeddah", region: "Makkah Region" },
      { name: "Makkah", region: "Makkah Region" },
      { name: "Taif", region: "Makkah Region" },
      { name: "Rabigh", region: "Makkah Region" },
      { name: "Khulais", region: "Makkah Region" },
      { name: "Al Lith", region: "Makkah Region" },
      { name: "Al Qunfudhah", region: "Makkah Region" },
      { name: "Al Jumum", region: "Makkah Region" },
      { name: "Bahrah", region: "Makkah Region" },
      { name: "Raniah", region: "Makkah Region" },
      { name: "Turabah", region: "Makkah Region" },
      { name: "Al Khurmah", region: "Makkah Region" },
      { name: "Madinah", region: "Madinah Region" },
      { name: "Yanbu", region: "Madinah Region" },
      { name: "Al Ula", region: "Madinah Region" },
      { name: "Badr", region: "Madinah Region" },
      { name: "Khaybar", region: "Madinah Region" },
      { name: "Mahd Al Dhahab", region: "Madinah Region" },
      { name: "Al Henakiyah", region: "Madinah Region" },
      { name: "Dammam", region: "Eastern Province" },
      { name: "Al Khobar", region: "Eastern Province" },
      { name: "Dhahran", region: "Eastern Province" },
      { name: "Jubail", region: "Eastern Province" },
      { name: "Al Qatif", region: "Eastern Province" },
      { name: "Al Ahsa", region: "Eastern Province" },
      { name: "Al Hofuf", region: "Eastern Province" },
      { name: "Al Mubarraz", region: "Eastern Province" },
      { name: "Hafar Al Batin", region: "Eastern Province" },
      { name: "Khafji", region: "Eastern Province" },
      { name: "Ras Tanura", region: "Eastern Province" },
      { name: "Abqaiq", region: "Eastern Province" },
      { name: "Qaryat Al Ulya", region: "Eastern Province" },
      { name: "Nairyah", region: "Eastern Province" },
      { name: "Saihat", region: "Eastern Province" },
      { name: "Safwa", region: "Eastern Province" },
      { name: "Buraidah", region: "Qassim Region" },
      { name: "Unaizah", region: "Qassim Region" },
      { name: "Al Rass", region: "Qassim Region" },
      { name: "Al Bukayriyah", region: "Qassim Region" },
      { name: "Al Badayea", region: "Qassim Region" },
      { name: "Riyadh Al Khabra", region: "Qassim Region" },
      { name: "Al Mithnab", region: "Qassim Region" },
      { name: "Uyun Al Jawa", region: "Qassim Region" },
      { name: "Hail", region: "Hail Region" },
      { name: "Baqaa", region: "Hail Region" },
      { name: "Ghazala", region: "Hail Region" },
      { name: "Al Shinan", region: "Hail Region" },
      { name: "Arar", region: "Northern Borders Region" },
      { name: "Rafha", region: "Northern Borders Region" },
      { name: "Turaif", region: "Northern Borders Region" },
      { name: "Al Uwayqilah", region: "Northern Borders Region" },
      { name: "Sakaka", region: "Al Jawf Region" },
      { name: "Dumat Al Jandal", region: "Al Jawf Region" },
      { name: "Qurayyat", region: "Al Jawf Region" },
      { name: "Tabarjal", region: "Al Jawf Region" },
      { name: "Tabuk", region: "Tabuk Region" },
      { name: "Al Wajh", region: "Tabuk Region" },
      { name: "Umluj", region: "Tabuk Region" },
      { name: "Duba", region: "Tabuk Region" },
      { name: "Haql", region: "Tabuk Region" },
      { name: "Tayma", region: "Tabuk Region" },
      { name: "Al Bad", region: "Tabuk Region" },
      { name: "Abha", region: "Asir Region" },
      { name: "Khamis Mushait", region: "Asir Region" },
      { name: "Ahad Rafidah", region: "Asir Region" },
      { name: "Bisha", region: "Asir Region" },
      { name: "Muhayil Aseer", region: "Asir Region" },
      { name: "Sarat Abidah", region: "Asir Region" },
      { name: "Rijal Almaa", region: "Asir Region" },
      { name: "Tathleeth", region: "Asir Region" },
      { name: "Balqarn", region: "Asir Region" },
      { name: "Al Namas", region: "Asir Region" },
      { name: "Jazan", region: "Jazan Region" },
      { name: "Sabya", region: "Jazan Region" },
      { name: "Samtah", region: "Jazan Region" },
      { name: "Abu Arish", region: "Jazan Region" },
      { name: "Bish", region: "Jazan Region" },
      { name: "Damad", region: "Jazan Region" },
      { name: "Farasan", region: "Jazan Region" },
      { name: "Najran", region: "Najran Region" },
      { name: "Sharurah", region: "Najran Region" },
      { name: "Hubuna", region: "Najran Region" },
      { name: "Badr Al Janub", region: "Najran Region" },
      { name: "Al Baha", region: "Al Baha Region" },
      { name: "Baljurashi", region: "Al Baha Region" },
      { name: "Al Mandaq", region: "Al Baha Region" },
      { name: "Qilwah", region: "Al Baha Region" },
      { name: "Al Aqiq", region: "Al Baha Region" },
    ],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    regionGroup: "GCC",
    cities: [
      { name: "Abu Dhabi", region: "Abu Dhabi" },
      { name: "Dubai", region: "Dubai" },
      { name: "Sharjah", region: "Sharjah" },
      { name: "Ajman", region: "Ajman" },
      { name: "Ras Al Khaimah", region: "Ras Al Khaimah" },
    ],
  },
  {
    code: "QA",
    name: "Qatar",
    regionGroup: "GCC",
    cities: [
      { name: "Doha", region: "Doha" },
      { name: "Al Wakrah", region: "Al Wakrah" },
      { name: "Al Rayyan", region: "Al Rayyan" },
    ],
  },
  {
    code: "BH",
    name: "Bahrain",
    regionGroup: "GCC",
    cities: [
      { name: "Manama", region: "Capital Governorate" },
      { name: "Muharraq", region: "Muharraq Governorate" },
      { name: "Riffa", region: "Southern Governorate" },
    ],
  },
  {
    code: "KW",
    name: "Kuwait",
    regionGroup: "GCC",
    cities: [
      { name: "Kuwait City", region: "Capital" },
      { name: "Hawalli", region: "Hawalli" },
      { name: "Ahmadi", region: "Ahmadi" },
    ],
  },
  {
    code: "OM",
    name: "Oman",
    regionGroup: "GCC",
    cities: [
      { name: "Muscat", region: "Muscat" },
      { name: "Salalah", region: "Dhofar" },
      { name: "Sohar", region: "Al Batinah North" },
    ],
  },
  {
    code: "EG",
    name: "Egypt",
    regionGroup: "MENA",
    cities: [
      { name: "Cairo", region: "Cairo" },
      { name: "Alexandria", region: "Alexandria" },
      { name: "Giza", region: "Giza" },
    ],
  },
  {
    code: "JO",
    name: "Jordan",
    regionGroup: "MENA",
    cities: [
      { name: "Amman", region: "Amman" },
      { name: "Aqaba", region: "Aqaba" },
      { name: "Irbid", region: "Irbid" },
    ],
  },
  {
    code: "LB",
    name: "Lebanon",
    regionGroup: "MENA",
    cities: [
      { name: "Beirut", region: "Beirut" },
      { name: "Tripoli", region: "North" },
      { name: "Sidon", region: "South" },
    ],
  },
  {
    code: "TR",
    name: "Turkey",
    regionGroup: "MENA",
    cities: [
      { name: "Istanbul", region: "Marmara" },
      { name: "Ankara", region: "Anatolia" },
      { name: "Izmir", region: "Aegean" },
    ],
  },
  {
    code: "GB",
    name: "United Kingdom",
    regionGroup: "EU",
    cities: [
      { name: "London", region: "England" },
      { name: "Manchester", region: "England" },
      { name: "Birmingham", region: "England" },
    ],
  },
  {
    code: "DE",
    name: "Germany",
    regionGroup: "EU",
    cities: [
      { name: "Berlin", region: "Berlin" },
      { name: "Munich", region: "Bavaria" },
      { name: "Frankfurt", region: "Hesse" },
    ],
  },
  {
    code: "FR",
    name: "France",
    regionGroup: "EU",
    cities: [
      { name: "Paris", region: "Île-de-France" },
      { name: "Lyon", region: "Auvergne-Rhône-Alpes" },
      { name: "Marseille", region: "Provence-Alpes-Côte d'Azur" },
    ],
  },
  {
    code: "IT",
    name: "Italy",
    regionGroup: "EU",
    cities: [
      { name: "Rome", region: "Lazio" },
      { name: "Milan", region: "Lombardy" },
      { name: "Naples", region: "Campania" },
    ],
  },
  {
    code: "ES",
    name: "Spain",
    regionGroup: "EU",
    cities: [
      { name: "Madrid", region: "Community of Madrid" },
      { name: "Barcelona", region: "Catalonia" },
      { name: "Valencia", region: "Valencian Community" },
    ],
  },
  {
    code: "US",
    name: "United States",
    regionGroup: "Global",
    cities: [
      { name: "New York", region: "New York" },
      { name: "Los Angeles", region: "California" },
      { name: "Chicago", region: "Illinois" },
    ],
  },
  {
    code: "CN",
    name: "China",
    regionGroup: "Global",
    cities: [
      { name: "Beijing", region: "Beijing" },
      { name: "Shanghai", region: "Shanghai" },
      { name: "Shenzhen", region: "Guangdong" },
    ],
  },
  {
    code: "IN",
    name: "India",
    regionGroup: "Global",
    cities: [
      { name: "New Delhi", region: "Delhi" },
      { name: "Mumbai", region: "Maharashtra" },
      { name: "Bengaluru", region: "Karnataka" },
    ],
  },
  {
    code: "ZA",
    name: "South Africa",
    regionGroup: "Global",
    cities: [
      { name: "Johannesburg", region: "Gauteng" },
      { name: "Cape Town", region: "Western Cape" },
      { name: "Durban", region: "KwaZulu-Natal" },
    ],
  },
];
