import { buildVendorRegistrationVerificationUrl } from "@/lib/utils";

type VendorApprovedTemplateInput = {
  vendorName: string;
  requestNumber: string;
};

type VendorRejectedTemplateInput = VendorApprovedTemplateInput & {
  reason?: string | null;
};

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function buildShell({
  title,
  preheader,
  accentColor,
  body,
}: {
  title: string;
  preheader: string;
  accentColor: string;
  body: string;
}) {
  return `
    <div role="article" aria-label="${escapeHtml(title)}" style="margin:0;background:#f4f2f6;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;color:#22161f;">
    <div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">
      ${escapeHtml(preheader)}
    </div>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;background:#f4f2f6;">
      <tr>
        <td style="padding:36px 16px;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;margin:0 auto;border-collapse:collapse;background:#ffffff;border-radius:18px;overflow:hidden;box-shadow:0 18px 48px rgba(27,16,51,0.14);">
            <tr>
              <td style="background:#1b1033;background-image:linear-gradient(135deg,#0b0b14 0%,#1b1033 54%,#2a1b4d 100%);padding:32px 34px;text-align:left;">
                <div style="font-size:11px;line-height:16px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#e5c98a;">
                  THE GATHERING KSA
                </div>
                <h1 style="margin:10px 0 0;font-size:24px;line-height:32px;font-weight:700;color:#ffffff;">
                  Procurement Operations Platform
                </h1>
                <div style="margin-top:20px;width:72px;height:3px;background:${accentColor};border-radius:999px;"></div>
              </td>
            </tr>
            <tr>
              <td style="padding:34px;">
                ${body}
              </td>
            </tr>
            <tr>
              <td style="padding:22px 34px 30px;border-top:1px solid #eee8f1;background:#fbfafc;">
                <p style="margin:0;font-size:12px;line-height:20px;color:#6b6270;">
                  Procurement Team<br />
                  The Gathering KSA
                </p>
                <p style="margin:14px 0 0;font-size:11px;line-height:18px;color:#8a8190;">
                  This message was generated by The Gathering KSA Procurement Operations Platform. Registration approval does not constitute a contract, purchase order, work order, award, or payment commitment.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
    </div>`;
}

function referenceBlock(requestNumber: string) {
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:24px 0;border-collapse:collapse;background:#f7f5fa;border:1px solid #e8e0ec;border-radius:12px;">
    <tr>
      <td style="padding:16px 18px;">
        <div style="font-size:11px;line-height:16px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;color:#6b6270;">Request Number</div>
        <div style="margin-top:5px;font-size:17px;line-height:24px;font-weight:700;color:#1b1033;">${escapeHtml(requestNumber)}</div>
      </td>
    </tr>
  </table>`;
}

function statusButton(requestNumber: string, background = "#1b1033") {
  const statusUrl = buildVendorRegistrationVerificationUrl(requestNumber);

  return `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:30px auto 4px;border-collapse:collapse;">
    <tr>
      <td style="border-radius:999px;background:${background};box-shadow:0 12px 28px rgba(27,16,51,0.18);">
        <a href="${escapeHtml(statusUrl)}" style="display:inline-block;padding:14px 28px;border-radius:999px;color:#ffffff;font-size:14px;line-height:18px;font-weight:700;text-decoration:none;">
          View Status
        </a>
      </td>
    </tr>
  </table>`;
}

export function vendorApprovedTemplate({
  vendorName,
  requestNumber,
}: VendorApprovedTemplateInput) {
  const safeVendorName = escapeHtml(vendorName);
  const body = `
    <div style="display:inline-block;margin:0 0 16px;padding:7px 11px;border-radius:999px;background:#ecfdf3;color:#16794a;font-size:11px;line-height:14px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;">
      Approved
    </div>
    <h2 style="margin:0;color:#151019;font-size:26px;line-height:34px;font-weight:700;">Registration Approved</h2>
    <p style="margin:18px 0 0;color:#4d4654;font-size:15px;line-height:26px;">Dear ${safeVendorName},</p>
    <p style="margin:14px 0 0;color:#4d4654;font-size:15px;line-height:26px;">Your supplier registration has been successfully approved by The Gathering KSA procurement team.</p>
    ${referenceBlock(requestNumber)}
    <p style="margin:0;color:#4d4654;font-size:15px;line-height:26px;">You may now be invited to participate in relevant procurement opportunities based on your approved profile and category classification.</p>
    ${statusButton(requestNumber, "#16794a")}
  `;

  return {
    subject: "Vendor Registration Approved - The Gathering KSA",
    html: buildShell({
      title: "Registration Approved",
      preheader: `Your supplier registration request ${requestNumber} has been approved.`,
      accentColor: "#22c55e",
      body,
    }),
  };
}

export function vendorRejectedTemplate({
  vendorName,
  requestNumber,
  reason,
}: VendorRejectedTemplateInput) {
  const safeVendorName = escapeHtml(vendorName);
  const reasonHtml = reason
    ? `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:22px 0;border-collapse:collapse;background:#fbfafc;border:1px solid #e8e0ec;border-radius:12px;">
        <tr>
          <td style="padding:16px 18px;">
            <div style="font-size:11px;line-height:16px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;color:#6b6270;">Review Note</div>
            <div style="margin-top:6px;font-size:14px;line-height:24px;color:#4d4654;">${escapeHtml(reason)}</div>
          </td>
        </tr>
      </table>`
    : "";
  const body = `
    <div style="display:inline-block;margin:0 0 16px;padding:7px 11px;border-radius:999px;background:#f7f5fa;color:#5f5665;font-size:11px;line-height:14px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;">
      Reviewed
    </div>
    <h2 style="margin:0;color:#151019;font-size:26px;line-height:34px;font-weight:700;">Registration Update</h2>
    <p style="margin:18px 0 0;color:#4d4654;font-size:15px;line-height:26px;">Dear ${safeVendorName},</p>
    <p style="margin:14px 0 0;color:#4d4654;font-size:15px;line-height:26px;">Thank you for submitting your supplier registration request. After review, your request has not been approved at this stage.</p>
    ${referenceBlock(requestNumber)}
    ${reasonHtml}
    <p style="margin:0;color:#4d4654;font-size:15px;line-height:26px;">You are welcome to update your information and reapply in the future when the requested requirements are available.</p>
    ${statusButton(requestNumber)}
  `;

  return {
    subject: "Vendor Registration Update - The Gathering KSA",
    html: buildShell({
      title: "Registration Update",
      preheader: `Your supplier registration request ${requestNumber} has been reviewed.`,
      accentColor: "#c8a45c",
      body,
    }),
  };
}
