import type { ReactNode } from "react";
import { render, toPlainText } from "@react-email/render";
import { Resend, type ErrorResponse } from "resend";
import type { VendorEvaluationEvaluatorRole, WorkflowEmailEvent } from "@prisma/client";

import {
  CertificateIssuedEmail,
  PMApprovalConfirmationEmail,
  PMApprovalRequestEmail,
  WorkflowUpdateEmail,
} from "@/emails";
import {
  HEAD_OF_PROJECTS_EMAIL,
  PROCUREMENT_TEAM_EMAILS,
  VENDOR_EVALUATION_ROLE_LABELS,
} from "@/lib/constants";
import type { WorkflowRoutingPolicy } from "@/lib/workflow-routing";
import { WORKFLOW_EMAIL_ROUTING_POLICIES } from "@/lib/workflow-routing";
import { getResendApiKey, getResendFromEmail } from "@/lib/env";
import { prisma } from "@/lib/prisma";
import { absoluteUrl, buildPmApprovalUrl, buildVerifyUrl } from "@/lib/utils";
import { generateCertificatePdfBuffer } from "@/server/services/pdf-service";
import { resolveWorkflowEmailRecipients } from "@/server/services/workflow-email-settings-service";
import {
  resolveWorkflowEmailRouting,
  type WorkflowRoutingContext,
} from "@/server/services/workflow-routing-service";

export type EmailTestTemplate =
  | "PM_APPROVAL_REQUEST"
  | "PROCUREMENT_NOTIFICATION"
  | "CERTIFICATE_ISSUED"
  | "CERTIFICATE_REOPENED";

type AttachmentInput = {
  filename: string;
  content: Buffer;
};

type RenderableEmailPayload = {
  from: string;
  to: string | string[];
  cc?: string[];
  subject: string;
  react?: ReactNode;
  html?: string;
  text?: string;
  attachments?: AttachmentInput[];
};

type FallbackEmailContentInput = {
  heading: string;
  intro: string;
  rows?: Array<{
    label: string;
    value: string | null | undefined;
  }>;
  actionLabel?: string;
  actionUrl?: string;
  footerNote?: string;
};

class EmailDeliveryError extends Error {
  constructor(
    message: string,
    readonly details?: {
      resendError?: ErrorResponse;
      response?: unknown;
    },
  ) {
    super(message);
    this.name = "EmailDeliveryError";
  }
}

function normalizeEmail(email: string) {
  return email.trim().toLowerCase();
}

function uniqueEmails(
  emails: Array<string | null | undefined>,
  excluded: string[] = [],
) {
  const excludedSet = new Set(excluded.map(normalizeEmail));
  const values = new Set<string>();

  for (const email of emails) {
    if (!email) {
      continue;
    }

    const normalized = normalizeEmail(email);
    if (!normalized || excludedSet.has(normalized)) {
      continue;
    }

    values.add(normalized);
  }

  return [...values];
}

function getResendConfig(options?: { requireConfigured?: boolean }) {
  const apiKey = process.env.RESEND_API_KEY;
  const fromEmail = process.env.RESEND_FROM_EMAIL;

  if (!apiKey || !fromEmail) {
    if (options?.requireConfigured) {
      throw new Error(
        "Set RESEND_API_KEY and RESEND_FROM_EMAIL before sending emails.",
      );
    }

    console.warn("[email] Resend is not configured. Email delivery skipped.");
    return null;
  }

  return {
    resend: new Resend(getResendApiKey()),
    from: getResendFromEmail(),
  };
}

function formatSandboxGuidance(error: ErrorResponse) {
  const message = error.message.toLowerCase();
  const isSandboxLike =
    error.statusCode === 403 &&
    (error.name === "validation_error" ||
      message.includes("testing") ||
      message.includes("sandbox") ||
      message.includes("verify") ||
      message.includes("owner email"));

  if (!isSandboxLike) {
    return null;
  }

  return [
    "This Resend account appears to still be in testing or sandbox mode.",
    "Until you verify a sending domain, Resend usually allows delivery only to the owner email address.",
    "Verify your sending domain and use that verified sender before sending to other recipients.",
  ].join(" ");
}

function buildResendFailureMessage(error: ErrorResponse) {
  const exactMessage = error.message?.trim() || "Resend rejected the email.";
  const sandboxGuidance = formatSandboxGuidance(error);

  if (!sandboxGuidance) {
    return exactMessage;
  }

  return `${exactMessage} ${sandboxGuidance}`;
}

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function buildFallbackEmailContent(input: FallbackEmailContentInput) {
  const rows = (input.rows ?? []).filter((row) => row.value);
  const footerNote =
    input.footerNote ??
    "This message was generated by The Gathering KSA Completion Certificate Management System.";

  const actionHtml =
    input.actionLabel && input.actionUrl
      ? `<p style="margin:24px 0 0;"><a href="${escapeHtml(input.actionUrl)}" style="display:inline-block;border-radius:999px;background:#311347;color:#ffffff;padding:14px 24px;font-weight:700;font-size:14px;text-decoration:none;">${escapeHtml(input.actionLabel)}</a></p>`
      : "";

  const rowsHtml = rows.length
    ? `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-top:20px;border-collapse:collapse;">${rows
        .map(
          (row) =>
            `<tr><td style="padding:0 0 6px;color:#6e5b67;font-size:12px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;">${escapeHtml(row.label)}</td></tr><tr><td style="padding:0 0 14px;color:#22161f;font-size:15px;line-height:24px;">${escapeHtml(String(row.value))}</td></tr>`,
        )
        .join("")}</table>`
    : "";

  const html = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charSet="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(input.heading)}</title>
  </head>
  <body style="margin:0;background:#f6f0e8;font-family:'Public Sans','Segoe UI',Tahoma,Arial,sans-serif;padding:20px 0;">
    <div style="max-width:640px;margin:0 auto;background:#ffffff;border:1px solid #ded4c8;border-radius:20px;overflow:hidden;">
      <div style="padding:28px 32px;background:linear-gradient(135deg,#311347 0%,#4d226a 68%,#d78439 100%);">
        <p style="margin:0;color:#fff7f1;font-size:12px;font-weight:700;letter-spacing:0.24em;text-transform:uppercase;">The Gathering KSA</p>
        <h1 style="margin:16px 0 0;color:#ffffff;font-size:28px;line-height:1.2;">${escapeHtml(input.heading)}</h1>
      </div>
      <div style="padding:28px 32px 24px;">
        <p style="margin:0;color:#22161f;font-size:16px;line-height:28px;">${escapeHtml(input.intro)}</p>
        ${rowsHtml}
        ${actionHtml}
      </div>
      <div style="border-top:1px solid #ded4c8;padding:16px 32px 28px;">
        <p style="margin:0;color:#6e5b67;font-size:12px;line-height:20px;">${escapeHtml(footerNote)}</p>
      </div>
    </div>
  </body>
</html>`;

  const textLines = [
    input.heading,
    "",
    input.intro,
    "",
    ...rows.flatMap((row) => [`${row.label}: ${row.value}`, ""]),
    input.actionLabel && input.actionUrl
      ? `${input.actionLabel}: ${input.actionUrl}`
      : "",
    "",
    footerNote,
  ].filter(Boolean);

  return {
    html,
    text: textLines.join("\n"),
  };
}

async function resolveEmailBody(
  label: string,
  payload: RenderableEmailPayload,
  fallback?: FallbackEmailContentInput,
) {
  if (payload.react) {
    try {
      const html = await render(payload.react);
      const text =
        payload.text?.trim() || toPlainText(html).trim() || payload.subject;

      return {
        html,
        text,
        renderMode: "react" as const,
      };
    } catch (error) {
      console.error("[email] react render failed", {
        label,
        subject: payload.subject,
        error,
      });
    }
  }

  if (payload.html || payload.text) {
    const html =
      payload.html ??
      buildFallbackEmailContent({
        heading: payload.subject,
        intro: payload.text ?? payload.subject,
      }).html;
    const text =
      payload.text ?? (toPlainText(html).trim() || payload.subject);

    return {
      html,
      text,
      renderMode: "plain" as const,
    };
  }

  if (fallback) {
    const content = buildFallbackEmailContent(fallback);
    return {
      ...content,
      renderMode: "fallback" as const,
    };
  }

  const safeFallback = buildFallbackEmailContent({
    heading: payload.subject,
    intro: payload.subject,
  });

  return {
    ...safeFallback,
    renderMode: "fallback" as const,
  };
}

async function getProcurementTeamRecipients(excluded: string[] = []) {
  const users = await prisma.user.findMany({
    where: {
      isActive: true,
      email: {
        in: [...PROCUREMENT_TEAM_EMAILS],
      },
    },
    select: {
      email: true,
    },
  });

  const recipients = uniqueEmails(
    users.map((user) => user.email),
    excluded,
  );

  const missingEmails = [...PROCUREMENT_TEAM_EMAILS].filter(
    (email) => !users.some((user) => normalizeEmail(user.email) === email),
  );

  if (missingEmails.length > 0) {
    console.warn("[email] missing procurement users for workflow email", {
      missingEmails,
    });
  }

  return recipients;
}

async function resolveConfiguredWorkflowRecipients(input: {
  event: WorkflowEmailEvent;
  defaultTo: string[];
  defaultCc?: string[];
}) {
  const resolved = await resolveWorkflowEmailRecipients({
    event: input.event,
    defaultTo: input.defaultTo,
    defaultCc: input.defaultCc,
  });

  if (!resolved.enabled) {
    console.warn("[email] workflow email disabled by settings", {
      event: input.event,
    });
  }

  if (resolved.enabled && resolved.to.length === 0) {
    console.warn("[email] workflow email has no recipients after settings resolution", {
      event: input.event,
    });
  }

  return resolved;
}

export async function sendGovernedWorkflowEmail(input: {
  event: WorkflowEmailEvent;
  label: string;
  defaultTo?: string[];
  defaultCc?: string[];
  subject: string;
  heading: string;
  intro: string;
  rows?: Array<{
    label: string;
    value: string | null | undefined;
  }>;
  actionLabel?: string;
  actionUrl?: string;
  logContext?: Record<string, unknown>;
  routingPolicy?: WorkflowRoutingPolicy;
  routingContext?: WorkflowRoutingContext;
}) {
  const routedRecipients =
    input.routingPolicy && input.routingContext
      ? await resolveWorkflowEmailRouting({
          event: input.event,
          policy: input.routingPolicy,
          context: input.routingContext,
        })
      : await resolveConfiguredWorkflowRecipients({
          event: input.event,
          defaultTo: input.defaultTo ?? [],
          defaultCc: input.defaultCc,
        });

  if (!routedRecipients.enabled || routedRecipients.to.length === 0) {
    return {
      skipped: true,
      reason: routedRecipients.enabled ? "NO_ROUTED_RECIPIENTS" : "DISABLED_BY_SETTINGS",
    };
  }

  return sendResendEmail(input.label, {
    payload: {
      from: "",
      to: routedRecipients.to,
      cc: routedRecipients.cc,
      subject: input.subject,
      react: WorkflowUpdateEmail({
        preview: input.subject,
        heading: input.heading,
        intro: input.intro,
        rows: input.rows,
        actionLabel: input.actionLabel,
        actionUrl: input.actionUrl,
      }),
    },
    fallback: {
      heading: input.heading,
      intro: input.intro,
      rows: input.rows,
      actionLabel: input.actionLabel,
      actionUrl: input.actionUrl,
    },
    logContext: input.logContext,
  });
}

async function sendResendEmail(
  label: string,
  options: {
    requireConfigured?: boolean;
    payload: RenderableEmailPayload;
    fallback?: FallbackEmailContentInput;
    logContext?: Record<string, unknown>;
  },
) {
  const config = getResendConfig({
    requireConfigured: options.requireConfigured,
  });

  if (!config) {
    console.warn("[email] skipped", {
      label,
      recipient: options.payload.to,
      subject: options.payload.subject,
      reason: "RESEND_NOT_CONFIGURED",
      ...options.logContext,
    });
    return {
      skipped: true,
      reason: "RESEND_NOT_CONFIGURED",
    };
  }

  try {
    const body = await resolveEmailBody(label, options.payload, options.fallback);
    const response = await config.resend.emails.send({
      from: config.from,
      to: options.payload.to,
      cc: options.payload.cc,
      subject: options.payload.subject,
      html: body.html,
      text: body.text,
      attachments: options.payload.attachments,
    });

    if (response.error) {
      const failureMessage = buildResendFailureMessage(response.error);

      console.error("[email] failed", {
        label,
        recipient: options.payload.to,
        subject: options.payload.subject,
        to: options.payload.to,
        cc: options.payload.cc ?? [],
        success: false,
        renderMode: body.renderMode,
        resendResponse: response,
        resendError: response.error,
        ...options.logContext,
      });

      throw new EmailDeliveryError(failureMessage, {
        resendError: response.error,
        response,
      });
    }

    console.info("[email] sent", {
      label,
      recipient: options.payload.to,
      subject: options.payload.subject,
      to: options.payload.to,
      cc: options.payload.cc ?? [],
      success: true,
      renderMode: body.renderMode,
      resendResponse: response,
      ...options.logContext,
    });

    return response;
  } catch (error) {
    if (error instanceof EmailDeliveryError) {
      throw error;
    }

    console.error("[email] failed", {
      label,
      recipient: options.payload.to,
      subject: options.payload.subject,
      to: options.payload.to,
      cc: options.payload.cc ?? [],
      success: false,
      resendResponse: null,
      ...options.logContext,
      error,
    });
    throw error;
  }
}

async function buildEmailTestFixture() {
  const certificateCode = "TGCC-TG-EMAIL-2026-001";
  const projectName = "TG Internal Email Testing Project";
  const vendorName = "North Star Build Partners";

  const pdfBuffer = await generateCertificatePdfBuffer({
    id: "email-test-certificate",
    certificateCode,
    issueDate: new Date("2026-04-20"),
    completionDate: new Date("2026-04-17"),
    totalAmount: {
      toString() {
        return "1250000.00";
      },
    },
    executedScopeSummary:
      "End-to-end completion certificate email testing package for the internal workflow, including approval routing, procurement notification, and issued certificate delivery validation.",
    poNumber: "PO-EMAIL-TEST-001",
    contractNumber: "CNT-EMAIL-TEST-001",
    issuedAt: new Date("2026-04-20"),
    clientName: "The Gathering KSA",
    clientTitle: "Client Representative",
    approverName: "Abdulmajeed Al Hussien",
    approverTitle: "Procurement Lead",
    pmName: "Project Manager Preview",
    pmTitle: "Project Manager",
    project: {
      projectName,
      projectCode: "TG-EMAIL-2026",
      projectLocation: "Riyadh, KSA",
    },
    vendor: {
      vendorName,
    },
  });

  return {
    approvalUrl: buildPmApprovalUrl("email-test-preview-token"),
    certificateCode,
    pdfBuffer,
    poNumber: "PO-EMAIL-TEST-001",
    contractNumber: "CNT-EMAIL-TEST-001",
    projectName,
    verificationUrl: buildVerifyUrl(certificateCode),
    vendorName,
  };
}

export async function sendPmApprovalRequestEmail(input: {
  to: string;
  cc?: string[];
  approvalUrl: string;
  projectName: string;
  vendorName: string;
  poNumber: string;
  contractNumber?: string | null;
}) {
  const to = normalizeEmail(input.to);
  const procurementRecipients = await getProcurementTeamRecipients([to]);
  const routedRecipients = await resolveWorkflowEmailRouting({
    event: "PM_APPROVAL_REQUEST",
    policy: WORKFLOW_EMAIL_ROUTING_POLICIES.PM_APPROVAL_REQUEST,
    context: {
      projectManager: { email: to },
      procurementChainEmails: procurementRecipients,
      manualCcEmails: [HEAD_OF_PROJECTS_EMAIL, ...(input.cc ?? [])],
    },
  });

  if (!routedRecipients.enabled || routedRecipients.to.length === 0) {
    return {
      skipped: true,
      reason: routedRecipients.enabled ? "NO_ROUTED_RECIPIENTS" : "DISABLED_BY_SETTINGS",
    };
  }

  return sendResendEmail("pm-approval-request", {
    payload: {
      from: "",
      to: routedRecipients.to,
      cc: routedRecipients.cc,
      subject: `Approval Required - ${input.projectName}`,
      react: PMApprovalRequestEmail({
        projectName: input.projectName,
        vendorName: input.vendorName,
        poNumber: input.poNumber,
        contractNumber: input.contractNumber,
        approvalUrl: input.approvalUrl,
      }),
    },
    fallback: {
      heading: "Completion Certificate Approval Required",
      intro: `A completion certificate is ready for your review and approval for ${input.vendorName} under ${input.projectName}.`,
      rows: [
        { label: "Project", value: input.projectName },
        { label: "Vendor", value: input.vendorName },
        { label: "PO Reference", value: input.poNumber },
        { label: "Contract Reference", value: input.contractNumber },
      ],
      actionLabel: "Review and Approve",
      actionUrl: input.approvalUrl,
    },
    logContext: {
      projectName: input.projectName,
      vendorName: input.vendorName,
      headOfProjectsEmail: HEAD_OF_PROJECTS_EMAIL,
    },
  });
}

export async function sendPmDecisionNotificationEmail(input: {
  projectName: string;
  vendorName: string;
  statusText: "approved" | "rejected";
  notes?: string | null;
}) {
  const procurementRecipients = await getProcurementTeamRecipients();

  if (procurementRecipients.length === 0) {
    console.warn("[email] No active procurement recipients found.");
    return {
      skipped: true,
      reason: "NO_PROCUREMENT_RECIPIENTS",
    };
  }

  const routedRecipients = await resolveWorkflowEmailRouting({
    event: "PM_DECISION_NOTIFICATION",
    policy: WORKFLOW_EMAIL_ROUTING_POLICIES.PM_DECISION_NOTIFICATION,
    context: {
      procurementChainEmails: procurementRecipients,
    },
  });

  if (!routedRecipients.enabled || routedRecipients.to.length === 0) {
    return {
      skipped: true,
      reason: routedRecipients.enabled ? "NO_ROUTED_RECIPIENTS" : "DISABLED_BY_SETTINGS",
    };
  }

  return sendResendEmail("pm-decision-notification", {
    payload: {
      from: "",
      to: routedRecipients.to,
      cc: routedRecipients.cc,
      subject: `Project Manager ${input.statusText === "approved" ? "Approved" : "Rejected"} - ${input.projectName}`,
      react: PMApprovalConfirmationEmail({
        projectName: input.projectName,
        vendorName: input.vendorName,
        statusText: input.statusText,
        notes: input.notes,
      }),
    },
    fallback: {
      heading: `Project Manager ${input.statusText === "approved" ? "Approved" : "Rejected"} Certificate`,
      intro: `The Project Manager has ${input.statusText} the completion certificate for ${input.vendorName} under ${input.projectName}.`,
      rows: [{ label: "Notes", value: input.notes }],
    },
    logContext: {
      projectName: input.projectName,
      vendorName: input.vendorName,
      statusText: input.statusText,
    },
  });
}

export async function sendIssuedCertificateEmail(input: {
  to: string;
  cc: string[];
  projectName: string;
  vendorName: string;
  certificateCode: string;
  verificationUrl: string;
  pdfBuffer: Buffer;
}) {
  const to = normalizeEmail(input.to);
  const normalizedCc = uniqueEmails(input.cc, [to]);
  const procurementRecipients = await getProcurementTeamRecipients([
    to,
    ...normalizedCc,
  ]);
  const routedRecipients = await resolveWorkflowEmailRouting({
    event: "FINAL_CERTIFICATE_ISSUED",
    policy: WORKFLOW_EMAIL_ROUTING_POLICIES.FINAL_CERTIFICATE_ISSUED,
    context: {
      manualToEmails: [to],
      projectManager: { email: normalizedCc[0] ?? null },
      procurementChainEmails: procurementRecipients,
    },
  });

  if (!routedRecipients.enabled || routedRecipients.to.length === 0) {
    return {
      skipped: true,
      reason: routedRecipients.enabled ? "NO_ROUTED_RECIPIENTS" : "DISABLED_BY_SETTINGS",
    };
  }

  return sendResendEmail("certificate-issued", {
    payload: {
      from: "",
      to: routedRecipients.to,
      cc: routedRecipients.cc,
      subject: `Completion Certificate Issued - ${input.projectName}`,
      react: CertificateIssuedEmail({
        projectName: input.projectName,
        vendorName: input.vendorName,
        certificateCode: input.certificateCode,
        verificationUrl: input.verificationUrl,
      }),
      attachments: [
        {
          filename: `${input.certificateCode}.pdf`,
          content: input.pdfBuffer,
        },
      ],
    },
    fallback: {
      heading: "Completion Certificate Issued",
      intro: `The final completion certificate for ${input.vendorName} under ${input.projectName} has been issued and is attached to this email.`,
      rows: [
        { label: "Certificate Code", value: input.certificateCode },
        { label: "Project", value: input.projectName },
        { label: "Vendor", value: input.vendorName },
      ],
      actionLabel: "Verify Certificate",
      actionUrl: input.verificationUrl,
    },
    logContext: {
      projectName: input.projectName,
      vendorName: input.vendorName,
      certificateCode: input.certificateCode,
    },
  });
}

export async function sendCertificateReopenedEmail(input: {
  projectName: string;
  vendorName: string;
  certificateCode: string;
  reopenedByName: string;
  reopenUrl: string;
  projectManagerEmail?: string | null;
}) {
  const procurementRecipients = await getProcurementTeamRecipients();

  if (procurementRecipients.length === 0) {
    console.warn("[email] No active procurement recipients found.");
    return {
      skipped: true,
      reason: "NO_PROCUREMENT_RECIPIENTS",
    };
  }

  const routedRecipients = await resolveWorkflowEmailRouting({
    event: "CERTIFICATE_REOPENED",
    policy: WORKFLOW_EMAIL_ROUTING_POLICIES.CERTIFICATE_REOPENED,
    context: {
      procurementChainEmails: procurementRecipients,
      projectManager: { email: input.projectManagerEmail ?? null },
    },
  });

  if (!routedRecipients.enabled || routedRecipients.to.length === 0) {
    return {
      skipped: true,
      reason: routedRecipients.enabled ? "NO_ROUTED_RECIPIENTS" : "DISABLED_BY_SETTINGS",
    };
  }

  return sendResendEmail("certificate-reopened", {
    payload: {
      from: "",
      to: routedRecipients.to,
      cc: routedRecipients.cc,
      subject: `Certificate Reopened for Revision - ${input.projectName}`,
      react: WorkflowUpdateEmail({
        preview: `Certificate reopened for revision under ${input.projectName}`,
        heading: "Certificate Reopened for Revision",
        intro: `${input.vendorName} certificate under ${input.projectName} has been reopened for controlled revision.`,
        rows: [
          { label: "Certificate Code", value: input.certificateCode },
          { label: "Project", value: input.projectName },
          { label: "Vendor", value: input.vendorName },
          { label: "Reopened By", value: input.reopenedByName },
        ],
        actionLabel: "Review Certificate",
        actionUrl: input.reopenUrl,
      }),
    },
    fallback: {
      heading: "Certificate Reopened for Revision",
      intro: `${input.vendorName} certificate under ${input.projectName} has been reopened for controlled revision.`,
      rows: [
        { label: "Certificate Code", value: input.certificateCode },
        { label: "Project", value: input.projectName },
        { label: "Vendor", value: input.vendorName },
        { label: "Reopened By", value: input.reopenedByName },
      ],
      actionLabel: "Review Certificate",
      actionUrl: input.reopenUrl,
    },
    logContext: {
      projectName: input.projectName,
      vendorName: input.vendorName,
      certificateCode: input.certificateCode,
      reopenedByName: input.reopenedByName,
    },
  });
}

export async function sendVendorEvaluationRequestEmail(input: {
  to: string;
  evaluatorRole: VendorEvaluationEvaluatorRole;
  vendorName: string;
  vendorCode: string;
  projectName: string;
  projectCode: string;
  year: number;
  evaluationUrl: string;
}) {
  const reviewerLabel = VENDOR_EVALUATION_ROLE_LABELS[input.evaluatorRole];
  const to = normalizeEmail(input.to);
  const routedRecipients = await resolveWorkflowEmailRouting({
    event: "VENDOR_EVALUATION_REQUEST",
    policy: WORKFLOW_EMAIL_ROUTING_POLICIES.VENDOR_EVALUATION_REQUEST,
    context: {
      projectManager: { email: to },
      manualToEmails: [to],
    },
  });

  if (!routedRecipients.enabled || routedRecipients.to.length === 0) {
    return {
      skipped: true,
      reason: routedRecipients.enabled ? "NO_ROUTED_RECIPIENTS" : "DISABLED_BY_SETTINGS",
    };
  }

  return sendResendEmail("vendor-evaluation-request", {
    payload: {
      from: "",
      to: routedRecipients.to,
      cc: routedRecipients.cc,
      subject: `Vendor Evaluation Request - ${input.vendorName} (${input.year})`,
      react: WorkflowUpdateEmail({
        preview: `Vendor evaluation request for ${input.vendorName}`,
        heading: "Vendor Evaluation Request",
        intro: `Please complete the annual vendor evaluation for ${input.vendorName} as the ${reviewerLabel}.`,
        rows: [
          { label: "Vendor", value: input.vendorName },
          { label: "Vendor Code", value: input.vendorCode },
          { label: "Project", value: input.projectName },
          { label: "Project Code", value: input.projectCode },
          { label: "Evaluation Year", value: String(input.year) },
          { label: "Reviewer Role", value: reviewerLabel },
        ],
        actionLabel: "Open Evaluation",
        actionUrl: input.evaluationUrl,
      }),
    },
    fallback: {
      heading: "Vendor Evaluation Request",
      intro: `Please complete the annual vendor evaluation for ${input.vendorName} as the ${reviewerLabel}.`,
      rows: [
        { label: "Vendor", value: input.vendorName },
        { label: "Vendor Code", value: input.vendorCode },
        { label: "Project", value: input.projectName },
        { label: "Project Code", value: input.projectCode },
        { label: "Evaluation Year", value: String(input.year) },
        { label: "Reviewer Role", value: reviewerLabel },
      ],
      actionLabel: "Open Evaluation",
      actionUrl: input.evaluationUrl,
    },
    logContext: {
      evaluatorRole: input.evaluatorRole,
      vendorName: input.vendorName,
      vendorCode: input.vendorCode,
      projectName: input.projectName,
      projectCode: input.projectCode,
      year: input.year,
    },
  });
}

export async function sendWorkflowEmailTest(input: {
  template: EmailTestTemplate;
  recipientEmail: string;
  requestedBy: string;
}) {
  const recipientEmail = normalizeEmail(input.recipientEmail);
  const fixture = await buildEmailTestFixture();

  switch (input.template) {
    case "PM_APPROVAL_REQUEST":
      return sendResendEmail("email-test-pm-approval-request", {
        requireConfigured: true,
        payload: {
          from: "",
          to: recipientEmail,
          subject: `[TEST] Approval Required - ${fixture.projectName}`,
          react: PMApprovalRequestEmail({
            projectName: fixture.projectName,
            vendorName: fixture.vendorName,
            poNumber: fixture.poNumber,
            contractNumber: fixture.contractNumber,
            approvalUrl: fixture.approvalUrl,
          }),
        },
        fallback: {
          heading: "Completion Certificate Approval Required",
          intro: `A completion certificate is ready for review and approval for ${fixture.vendorName} under ${fixture.projectName}.`,
          rows: [
            { label: "Project", value: fixture.projectName },
            { label: "Vendor", value: fixture.vendorName },
            { label: "PO Reference", value: fixture.poNumber },
            { label: "Contract Reference", value: fixture.contractNumber },
          ],
          actionLabel: "Review and Approve",
          actionUrl: fixture.approvalUrl,
        },
        logContext: {
          recipientEmail,
          requestedBy: input.requestedBy,
        },
      });
    case "PROCUREMENT_NOTIFICATION":
      return sendResendEmail("email-test-procurement-notification", {
        requireConfigured: true,
        payload: {
          from: "",
          to: recipientEmail,
          subject: `[TEST] Project Manager Approved - ${fixture.projectName}`,
          react: PMApprovalConfirmationEmail({
            projectName: fixture.projectName,
            vendorName: fixture.vendorName,
            statusText: "approved",
            notes:
              "This is a safe delivery test triggered from the admin dashboard.",
          }),
        },
        fallback: {
          heading: "Project Manager Approved Certificate",
          intro: `The Project Manager has approved the completion certificate for ${fixture.vendorName} under ${fixture.projectName}.`,
          rows: [
            {
              label: "Notes",
              value:
                "This is a safe delivery test triggered from the admin dashboard.",
            },
          ],
        },
        logContext: {
          recipientEmail,
          requestedBy: input.requestedBy,
        },
      });
    case "CERTIFICATE_ISSUED":
      return sendResendEmail("email-test-certificate-issued", {
        requireConfigured: true,
        payload: {
          from: "",
          to: recipientEmail,
          subject: `[TEST] Completion Certificate Issued - ${fixture.projectName}`,
          react: CertificateIssuedEmail({
            projectName: fixture.projectName,
            vendorName: fixture.vendorName,
            certificateCode: fixture.certificateCode,
            verificationUrl: fixture.verificationUrl,
          }),
          attachments: [
            {
              filename: `${fixture.certificateCode}.pdf`,
              content: fixture.pdfBuffer,
            },
          ],
        },
        fallback: {
          heading: "Completion Certificate Issued",
          intro: `The final completion certificate for ${fixture.vendorName} under ${fixture.projectName} has been issued and is attached to this email.`,
          rows: [
            { label: "Certificate Code", value: fixture.certificateCode },
            { label: "Project", value: fixture.projectName },
            { label: "Vendor", value: fixture.vendorName },
          ],
          actionLabel: "Verify Certificate",
          actionUrl: fixture.verificationUrl,
        },
        logContext: {
          recipientEmail,
          requestedBy: input.requestedBy,
        },
      });
    case "CERTIFICATE_REOPENED":
      return sendResendEmail("email-test-certificate-reopened", {
        requireConfigured: true,
        payload: {
          from: "",
          to: recipientEmail,
          subject: `[TEST] Certificate Reopened for Revision - ${fixture.projectName}`,
          react: WorkflowUpdateEmail({
            preview: `Certificate reopened for revision under ${fixture.projectName}`,
            heading: "Certificate Reopened for Revision",
            intro: `${fixture.vendorName} certificate under ${fixture.projectName} has been reopened for controlled revision.`,
            rows: [
              { label: "Certificate Code", value: fixture.certificateCode },
              { label: "Project", value: fixture.projectName },
              { label: "Vendor", value: fixture.vendorName },
              { label: "Reopened By", value: "Abdulmajeed Al Hussien" },
            ],
            actionLabel: "Review Certificate",
            actionUrl: absoluteUrl("/admin/certificates"),
          }),
        },
        fallback: {
          heading: "Certificate Reopened for Revision",
          intro: `${fixture.vendorName} certificate under ${fixture.projectName} has been reopened for controlled revision.`,
          rows: [
            { label: "Certificate Code", value: fixture.certificateCode },
            { label: "Project", value: fixture.projectName },
            { label: "Vendor", value: fixture.vendorName },
            { label: "Reopened By", value: "Abdulmajeed Al Hussien" },
          ],
          actionLabel: "Review Certificate",
          actionUrl: absoluteUrl("/admin/certificates"),
        },
        logContext: {
          recipientEmail,
          requestedBy: input.requestedBy,
        },
      });
    default:
      throw new Error("Unsupported email test template.");
  }
}
