import {
  Body,
  Button,
  Container,
  Head,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from "@react-email/components";
import * as React from "react";

import { BRAND_COLORS } from "@/lib/brand";

type EmailFrameProps = {
  preview: string;
  heading: string;
  intro: string;
  actionLabel?: string;
  actionUrl?: string;
  children?: React.ReactNode;
};

export function EmailFrame({
  preview,
  heading,
  intro,
  actionLabel,
  actionUrl,
  children,
}: EmailFrameProps) {
  return (
    <Html>
      <Head />
      <Preview>{preview}</Preview>
      <Body
        style={{
          backgroundColor: "#f6f0e8",
          fontFamily:
            '"Public Sans", "Segoe UI", Tahoma, Arial, sans-serif',
          padding: "20px 0",
        }}
      >
        <Container
          style={{
            backgroundColor: "#ffffff",
            borderRadius: "20px",
            border: `1px solid ${BRAND_COLORS.line}`,
            overflow: "hidden",
            maxWidth: "640px",
          }}
        >
          <Section
            style={{
              padding: "28px 32px",
              background:
                "linear-gradient(135deg, #311347 0%, #4d226a 68%, #d78439 100%)",
            }}
          >
            <Text
              style={{
                color: "#fff7f1",
                fontSize: "11px",
                fontWeight: 600,
                letterSpacing: "0.1em",
                margin: 0,
                textTransform: "uppercase",
              }}
            >
              The Gathering KSA
            </Text>
            <Text
              style={{
                color: "#ffffff",
                fontSize: "28px",
                fontWeight: 700,
                margin: "16px 0 0",
              }}
            >
              {heading}
            </Text>
          </Section>

          <Section style={{ padding: "28px 32px 12px" }}>
            <Text
              style={{
                color: "#22161f",
                fontSize: "16px",
                lineHeight: "28px",
                margin: 0,
              }}
            >
              {intro}
            </Text>
          </Section>

          {children}

          {actionLabel && actionUrl ? (
            <Section style={{ padding: "8px 32px 24px" }}>
              <Button
                href={actionUrl}
                style={{
                  backgroundColor: BRAND_COLORS.purple,
                  borderRadius: "999px",
                  color: "#ffffff",
                  display: "inline-block",
                  fontSize: "14px",
                  fontWeight: 700,
                  padding: "14px 24px",
                  textDecoration: "none",
                }}
              >
                {actionLabel}
              </Button>
            </Section>
          ) : null}

          <Hr
            style={{
              borderColor: BRAND_COLORS.line,
              margin: "0 32px",
            }}
          />
          <Section style={{ padding: "16px 32px 28px" }}>
            <Text
              style={{
                color: "#6e5b67",
                fontSize: "12px",
                lineHeight: "20px",
                margin: 0,
              }}
            >
              This message was generated by The Gathering KSA Procurement
              Operations Platform.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}
